namespace Terraria.GameContent.Drawing
{
	public enum ParticleOrchestraType : byte
	{
		Keybrand,
		FlameWaders,
		StellarTune,
		WallOfFleshGoatMountFlames,
		BlackLightningHit,
		RainbowRodHit,
		BlackLightningSmall,
		StardustPunch,
		PrincessWeapon,
		PaladinsHammer,
		NightsEdge,
		SilverBulletSparkle,
		TrueNightsEdge,
		Excalibur,
		TrueExcalibur,
		TerraBlade,
		ChlorophyteLeafCrystalPassive,
		ChlorophyteLeafCrystalShot,
		AshTreeShake,
		PetExchange,
		SlapHand,
		FlyMeal,
		GasTrap,
		ItemTransfer,
		ShimmerArrow,
		TownSlimeTransform,
		LoadoutChange,
		ShimmerBlock,
		Digestion,
		WaffleIron,
		PooFly,
		ShimmerTownNPC,
		ShimmerTownNPCSend
	}
}
